# Generated by Django 2.1.5 on 2019-01-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_front', models.CharField(max_length=200, verbose_name='front side')),
                ('card_back', models.CharField(max_length=200, verbose_name='back side')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, verbose_name='tag name')),
                ('previous_success_rate', models.IntegerField(default=0, verbose_name='previous success rate')),
                ('card_count', models.IntegerField(default=0, verbose_name='number of cards')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(related_name='cards', related_query_name='card', to='cards.Tag'),
        ),
    ]
