# Generated by Django 2.1.5 on 2019-01-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20190116_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='tag_count',
            field=models.IntegerField(default=0, verbose_name='number of tags'),
        ),
    ]
